apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.ops.csas.cz
spec:
  group: ops.csas.cz
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Application is the Schema for the applications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ApplicationSpec defines the desired state of Application
          properties:
            ignoreDifferences:
              description: IgnoreDifferences controls resources fields which should
                be ignored during comparison
              items:
                description: ResourceIgnoreDifferences contains resource filter and
                  list of json paths which should be ignored during comparison with
                  live state.
                properties:
                  group:
                    type: string
                  jsonPointers:
                    items:
                      type: string
                    type: array
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - jsonPointers
                - kind
                type: object
              type: array
            info:
              description: Infos contains a list of useful information (URLs, email
                addresses, and plain text) that relates to the application
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                - value
                type: object
              type: array
            source:
              description: Source is a reference to the location ksonnet application
                definition
              properties:
                chart:
                  description: Chart is a Helm chart name
                  type: string
                directory:
                  description: Directory holds path/directory specific options
                  properties:
                    jsonnet:
                      description: ApplicationSourceJsonnet holds jsonnet specific
                        options
                      properties:
                        extVars:
                          description: ExtVars is a list of Jsonnet External Variables
                          items:
                            description: JsonnetVar is a jsonnet variable
                            properties:
                              code:
                                type: boolean
                              name:
                                type: string
                              value:
                                type: string
                            required:
                            - name
                            - value
                            type: object
                          type: array
                        tlas:
                          description: TLAS is a list of Jsonnet Top-level Arguments
                          items:
                            description: JsonnetVar is a jsonnet variable
                            properties:
                              code:
                                type: boolean
                              name:
                                type: string
                              value:
                                type: string
                            required:
                            - name
                            - value
                            type: object
                          type: array
                      type: object
                    recurse:
                      type: boolean
                  type: object
                helm:
                  description: Helm holds helm specific options
                  properties:
                    parameters:
                      description: Parameters are parameters to the helm template
                      items:
                        description: HelmParameter is a parameter to a helm template
                        properties:
                          forceString:
                            description: ForceString determines whether to tell Helm
                              to interpret booleans and numbers as strings
                            type: boolean
                          name:
                            description: Name is the name of the helm parameter
                            type: string
                          value:
                            description: Value is the value for the helm parameter
                            type: string
                        type: object
                      type: array
                    releaseName:
                      description: The Helm release name. If omitted it will use the
                        application name
                      type: string
                    valueFiles:
                      description: ValuesFiles is a list of Helm value files to use
                        when generating a template
                      items:
                        type: string
                      type: array
                    values:
                      description: Values is Helm values, typically defined as a block
                      type: string
                  type: object
                ksonnet:
                  description: Ksonnet holds ksonnet specific options
                  properties:
                    environment:
                      description: Environment is a ksonnet application environment
                        name
                      type: string
                    parameters:
                      description: Parameters are a list of ksonnet component parameter
                        override values
                      items:
                        description: KsonnetParameter is a ksonnet component parameter
                        properties:
                          component:
                            type: string
                          name:
                            type: string
                          value:
                            type: string
                        required:
                        - name
                        - value
                        type: object
                      type: array
                  type: object
                kustomize:
                  description: Kustomize holds kustomize specific options
                  properties:
                    commonLabels:
                      additionalProperties:
                        type: string
                      description: CommonLabels adds additional kustomize commonLabels
                      type: object
                    images:
                      description: Images are kustomize image overrides
                      items:
                        type: string
                      type: array
                    namePrefix:
                      description: NamePrefix is a prefix appended to resources for
                        kustomize apps
                      type: string
                    nameSuffix:
                      description: NameSuffix is a suffix appended to resources for
                        kustomize apps
                      type: string
                  type: object
                path:
                  description: Path is a directory path within the Git repository
                  type: string
                plugin:
                  description: ConfigManagementPlugin holds config management plugin
                    specific options
                  properties:
                    env:
                      items:
                        properties:
                          name:
                            description: the name, usually uppercase
                            type: string
                          value:
                            description: the value
                            type: string
                        required:
                        - name
                        - value
                        type: object
                      type: array
                    name:
                      type: string
                  type: object
                repoURL:
                  description: RepoURL is the repository URL of the application manifests
                  type: string
                targetRevision:
                  description: TargetRevision defines the commit, tag, or branch in
                    which to sync the application to. If omitted, will sync to HEAD
                  type: string
              required:
              - repoURL
              type: object
            syncPolicy:
              description: SyncPolicy controls when a sync will be performed
              properties:
                automated:
                  description: Automated will keep an application synced to the target
                    revision
                  properties:
                    prune:
                      description: 'Prune will prune resources automatically as part
                        of automated sync (default: false)'
                      type: boolean
                    selfHeal:
                      description: 'SelfHeal enables auto-syncing if  (default: false)'
                      type: boolean
                  type: object
              type: object
          required:
          - source
          type: object
        status:
          description: ApplicationStatus defines the observed state of Application
          properties:
            lastUpdated:
              type: string
            ownedReferences:
              items:
                description: OwnedReference defines managed object
                properties:
                  apiVersion:
                    description: API version of the referenced object
                    type: string
                  kind:
                    description: Kind of the referenced object
                    type: string
                  name:
                    description: Name of the referenced object
                    type: string
                  namespace:
                    description: Namespace of the referenced object
                    type: string
                required:
                - apiVersion
                - kind
                - name
                - namespace
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
