kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csas-application-operator
subjects:
  - kind: ServiceAccount
    name: csas-application-operator
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: csas-application-operator
  apiGroup: rbac.authorization.k8s.io
