apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-application-operator
rules:
  - apiGroups:
      - ops.csas.cz
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ops.csas.cz
    resources:
      - applications/status
      - applications/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
