apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csas-application-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - ops.csas.cz
    resources:
      - applications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
