apiVersion: apps/v1
kind: Deployment
metadata:
  name: csas-application-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csas-application-operator
  template:
    metadata:
      labels:
        name: csas-application-operator
    spec:
      containers:
        - command:
            - csas-application-operator
          env:
            - name: WATCH_NAMESPACE
              value: "" # Note: This needs to be EMPTY in order to watch all namespaces
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csas-application-operator"
            - name: ARGOCD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ARGOCD_DESTINATION_SERVER
              value: "https://kubernetes.default.svc"
          image: csas/csas-application-operator
          imagePullPolicy: Always
          name: csas-application-operator
      serviceAccountName: csas-application-operator
