apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csas-application-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csas-application-operator
subjects:
  - kind: ServiceAccount
    name: csas-application-operator
