apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csas-application-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - ops.csas.cz
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
